### ISSUE TITLE
As a recipe developer, I want to be able to easily run (a series of) GDAL/OGR commands on Open Geospatial Data Cloud (OGDC)

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/simple-recipe-representation-exploration#1]
https://github.com/QGreenland-Net/simple-recipe-representation-exploration

**Comment by mfisher87** [comment]
I took a _very_ brief exploration of this in the above-linked repository. Where do we go from here?

**Comment by rushirajnenuji** [comment]
explored this as part of Apache Beam
